# Site settings
title: Mister WTF
email: hey@misterwtf.com
description: > # this means to ignore newlines until "baseurl:"
  Answering your digital WTF's
baseurl: "/MisterWTF" # the subpath of your site, e.g. /blog/
url: "http://www.misterwtf.com" # the base hostname & protocol for your site
twitter_username: heymisterwtf
github_username:  misterwtf

# Build settings
markdown: kramdown
